### ISSUE TITLE
Ksp stuck on "Loading part upgrades_

### ISSUE THREAD

**Issue by priyanshurohilla** [KSPModdingLibs/KSPBurst#1]
I have noticed that after using KSP burst, the game does not load at all. It gets stuck on "loading part upgrades" . As mentioned by principia author here - " Since 1.12 the mods that have DLLs with an empty "File Version" will fail to load and the game will be stuck on "loading part upgrades". "

So I think u have to do this. I have double checked kspburst is causing it to get stuck. You can refer to the whole discussion [Here](https://forum.kerbalspaceprogram.com/index.php?/topic/203262-stuck-on-loading-part-upgrades-112/)

**Comment by dkavolis** [comment]
Some of the Unity packages don't contain the file versions. Unity removes any custom `AssemblyInfo.cs` from the packages. Modifying any version fields using `pefile` and `ILMerge` still won't fix the issue in KSP even though every other tool shows the modified versions. I'm out of ideas short of fixing KSP itself.

**Comment by pleroy** [comment]
There is a long list of tools [here](https://stackoverflow.com/questions/284258/how-do-i-set-the-version-information-for-an-existing-exe-dll) that purport to patch the resources of a DLL.  I didn't try any of these.

**Comment by dkavolis** [comment]
Ok, it was actually an issue with `System.Runtime.CompilerServices.Unsafe.dll` and `Unity.Burst.Unsafe.dll` not having version resources at all, adding them in VS fixes the issues. KSP should still add a null check though.

**Comment by dkavolis** [comment]
Fixed in 4a175615f2425b67d857bb67471ee46c2ffd9728 by adding version resources to those DLLs

**Comment by miniskipper** [comment]
Error is still happening to me.
I even tried with a new KSP install without any mods and only installed KSPBurst 1.5.4.0 (tried via CKAN and github)

```[LOG 15:27:36.444] ******* Log Initiated for Kerbal Space Program - 1.12.1.3142 (LinuxPlayer) en-us *******
Kerbal Space Program - 1.12.1.3142 (LinuxPlayer) en-us
[...]
[EXC 15:27:37.846] ArgumentException: Version string portion was too short or too long.
        System.Version+VersionResult.SetFailure (System.Version+ParseFailureKind failure, System.String argument) (at <9577ac7a62ef43179789031239ba8798>:0)
        System.Version+VersionResult.SetFailure (System.Version+ParseFailureKind failure) (at <9577ac7a62ef43179789031239ba8798>:0)
        System.Version.TryParseVersion (System.String version, System.Version+VersionResult& result) (at <9577ac7a62ef43179789031239ba8798>:0)
        System.Version.Parse (System.String input) (at <9577ac7a62ef43179789031239ba8798>:0)
        System.Version..ctor (System.String version) (at <9577ac7a62ef43179789031239ba8798>:0)
        AssemblyLoader.LoadPluginInfo (System.IO.FileInfo file, System.String url, ConfigNode assemblyNode) (at <aaf41dd1ee6048d78d73af0eb6ffa814>:0)
        GameDatabase+<LoadObjects>d__90.MoveNext () (at <aaf41dd1ee6048d78d73af0eb6ffa814>:0)
        UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2425394cf09642369e2109953e31f62b>:0)
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        <CreateDatabase>d__71:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        GameDatabase:StartLoad()
        <LoadSystems>d__11:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        LoadingScreen:Start()
[..]
[EXC 15:34:02.018] NullReferenceException: Object reference not set to an instance of an object
        GameDatabase.CleanupLoaders () (at <aaf41dd1ee6048d78d73af0eb6ffa814>:0)
        GameDatabase+<CreateDatabase>d__71.MoveNext () (at <aaf41dd1ee6048d78d73af0eb6ffa814>:0)
        UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2425394cf09642369e2109953e31f62b>:0)
```

I suspect the Linux version behaves different in this regard? Does anyone have a clue?

**Comment by dkavolis** [comment]
I wouldn't expect the linux version to be any different. Without attaching a debugger and breaking on the exception I can't know what is going wrong from the stack trace alone and I don't have a linux machine to this on.

**Comment by miniskipper** [comment]
That's what i found:

![grafik](https://user-images.githubusercontent.com/2269291/127613074-d7ca3f69-f7bb-456d-adbb-6750324a4be5.png)

Strange, cause that's on of the dlls you updated.

![grafik](https://user-images.githubusercontent.com/2269291/127613685-8510b88e-7f2a-4f0d-8fb3-d26408356cfa.png)

Even stranger: FilaMajorPart is set to 1, but FileVersion is an empty string.

**Comment by dkavolis** [comment]
For some reason only adding version through Visual Studio made file version show up on `WSL` a7d4c9a622a702db44dae070c3d3d07cc769a9d7
@miniskipper try the latest version

**Comment by miniskipper** [comment]
Looks promising:
![grafik](https://user-images.githubusercontent.com/2269291/127644924-71c3aa40-d8e4-43bd-811f-45bd09948750.png)

Will try the game at the evening, when I'm home.
